version: "3.9"
services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: mastering
    ports:
      - "6432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
    ports:
      - "5678:5672" # AMQP
      - "15678:15672" # Management UI
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console UI
    volumes:
      - minio_data:/data

  create-bucket:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c"]
    command: >-
      "sleep 2 &&
       mc alias set local http://minio:9000 minio minio123 &&
       mc mb -p local/$${S3_BUCKET} || true &&
       mc policy set public local/$${S3_BUCKET} || true &&
       echo 'Bucket ensured' && sleep 2"
    environment:
      S3_BUCKET: audio

volumes:
  pg_data:
  rabbit_data:
  minio_data:
