"""Asset Name

Revision ID: 202509271319
Revises: 202509271257
Create Date: 2025-09-27 11:19:50.175061+00:00

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202509271319"
down_revision = "202509271257"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assets", sa.Column("file_name", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "file_name")
    # ### end Alembic commands ###
